version: '27.0.3'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-f*%&#2yr6$$u(%fk4cbc($$4&!&gw-o08fb78_za#nfdo85m7yyy"
      - "DJANGO_DEBUG=True"


  db:
    image: postgres:16
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
